--Total no of customers in database
Select count(customer_id ) as tot_customers
	from customers
--Find top 5 best products by quantity sold.
Select product_id,sum(quantity)
	from orders
	group by product_id
	order by 2 desc
	limit 5

--What is the total revenue generated.
--select * from orders
select sum(sale) from orders
--How much products do we have.
select count(distinct product_id)
from orders
--Find out top 5 order details by sales amount.
select order_id,max(sale)
from orders
group by order_id
order by max(sale) desc
limit 5
--What is the average order value.
select avg(sale) from orders
--What is the total sale for goa.
select sum(sale)from orders
where state = 'Goa'
--How many unique customers placed orders.
select count(distinct(customer_id)) 
from orders
--What is the total sale revenue generated by each states.
select sum(sale) as total_sale,
	state
from orders
group by 2
order by 1 desc
--How many orders were placed by each customer,and how much avg order quantity.
select count(  order_id),
	customer_id,
	avg(quantity) avg_order_quantity
from orders
group by customer_id

--Which category has max avg sales amount per order.
select category,avg(sale),count(*)
from orders
group by 1
order by 2 desc
--select * from orders
--Identify the top 3 best selling products (sub cat) in terms of tot quantity sold.
select sub_category, 
	max(quantity)
from orders
group by 1
order by 2 desc
limit 3
--Find top 3 products having revenue > 10000.
select product_id,sum(sale)
from orders
group by 1
having sum(sale) > 10000
order by 2 desc
limit 3


--Find customers name total order and tot revenue.
select c.customer_name,
	o.sale,o.quantity
from 
	customers c right join orders o
    on c.customer_id = o.customer_id
	
--Identify all orders that have been returned,along with details of return.
select customer_id,
	count(o.order_id),
	count(r.return_id)
from orders o
 left join returns r
on o.order_id = r.order_id
group by 1
--select * from returns
--Find all instances where products sold,returned or both along with details.
select o.product_id,
	count(o.seller_id) as sold,
	count(r.return_id) as returned
from 
	orders o full join returns r
    on o.order_id = r.order_id
group by 1
--Find top 5 states by total orders where each state sale is greater than average orders across orders
Select * from orders

Select state, count(order_id) as total_orders,
sum(sale) as total_sale
from orders
	group by state
having sum(sale) > (
Select avg(sale)
from  orders
  )
ORDER BY
  total_sale DESC
LIMIT
  5;

--Find the details of top 5 products with the highest total sales
--where tot sales of each product is greater than the avg sales of all products.

	
Select * from
	(Select p.product_id,
	p.product_name,
    cast(sum(o.sale) as int) tot_sale
from products p inner join orders o
	on
p.product_id = o.product_id	
	group by product_name,p.product_id)  total_sales_by_products
	where tot_sale >
	(Select avg(sale) from orders
	)
	order by tot_sale desc
	limit 5;
	
--
